// packages/vue/src/select-input/SelectInput.vue
<script setup lang="ts">
import useSelectInput from './useSelectInput';
import type { SelectInputProps } from './index.types';
import { KiCheveronDownSolid } from '@kedataindo/vue-icons';
import { Tag } from '../tag';
import { SelectPicker } from '../select-picker';
import FadeTransition from '../FadeTransition.vue';

const props = withDefaults(defineProps<SelectInputProps>(), {
  mode: 'single',
});
const value = defineModel<string | string[]>({
  default: '',
  set: (value: string | string[]) => {
    if (props.mode === 'single') {
      isOpen.value = false;
    }
    return value;
  },
});
const isOpen = defineModel<boolean>('is-open', {
  default: false,
});
const searchTerm = defineModel<string>('search-term', {
  default: '',
});

const { isPlaceholderShown, selectedOptions, valueModel, ...api } =
  useSelectInput(props, {
    value,
    isOpen,
    searchTerm,
  });
</script>

<template>
  <button v-bind="api.getRootProps()">
    <div v-bind="api.getInputWrapperProps()">
      <div v-bind="api.getValueProps()">
        <template v-if="isPlaceholderShown">
          {{ props.placeholder }}
        </template>
        <template v-else>
          <template v-if="api.mode.value === 'single'">
            {{ selectedOptions[0]?.label }}
          </template>
          <template v-if="api.mode.value === 'multiple'">
            <Tag
              v-for="option in selectedOptions"
              :closeable="true"
              :key="option.value"
              @keydown="
                (e: any) => {
                  e.stopPropagation();
                }
              "
              @click="
                (e: any) => {
                  e.stopPropagation();
                  api.removeValue(option.value);
                }
              "
            >
              {{ option.label }}
            </Tag>
          </template>
        </template>
      </div>

      <KiCheveronDownSolid v-bind="api.getIndicatorProps()" />
    </div>
  </button>

  <FadeTransition>
    <div v-if="api.isOpen.value" v-bind="api.getPositionerProps()">
      <div v-bind="api.getContentProps()">
        <SelectPicker
          v-bind="api.getSelectPickerProps()"
          v-model="valueModel"
        />
      </div>
    </div>
  </FadeTransition>
</template>

// packages/solid/src/select-input/select-input.tsx
import useSelectInput from './use-select-input';
import { Tag } from '../tag';
import { useTwMerge } from '../tw-merge';
import type { SelectInputProps } from './index.types';
import type { Component } from 'solid-js';
import { KiCheveronDownSolid } from '@kedataindo/solid-icons';
import { SelectPicker } from '../select-picker';

const SelectField: Component<SelectInputProps> = (props) => {
  const api = useSelectInput(props);

  return (
    <>
      <button {...api.getRootProps()}>
        <div {...api.getInputWrapperProps()}>
          {/* {startAddon && <div {...api.getStartAddonProps()}>{startAddon}</div>} */}

          <div {...api.getValueProps()}>
            {(() => {
              if (api.isPlaceholderShow()) {
                return api.placeholder();
              }

              if (!api.multiple()) {
                return api.selectedOptions()[0].label;
              }

              return api.selectedOptions().map((item) => {
                return (
                  <Tag
                    closeable
                    onKeyDown={(e: any) => {
                      e.stopPropagation();

                      if (e.key === 'Escape') {
                        // buttonRef.current?.focus();
                      }
                    }}
                    onClick={(e: any) => {
                      e.stopPropagation();
                      api.removeValue(item.value);
                    }}
                  >
                    {item.label}
                  </Tag>
                );
              });
            })()}
          </div>

          <KiCheveronDownSolid {...api.getIndicatorProps()} />
        </div>
      </button>
      {api.isPresence() && (
        <div {...api.getPositionerProps()}>
          <div {...api.getContentProps()}>
            <SelectPicker {...api.getSelectPickerProps()} />
          </div>
        </div>
      )}
    </>
  );
};

export default SelectField;
