// packages/solid/src/dialog/dialog-header.tsx
import useDialogHeader from './use-dialog-header';
import { KiCloseSolid } from '@kedataindo/solid-icons';
import type { DialogHeaderProps } from './index.types';
import type { Component } from 'solid-js';

const DialogHeader: Component<DialogHeaderProps> = (props) => {
  const api = useDialogHeader(props);

  return (
    <header {...api.getRootProps()}>
      <span {...api.getTitleProps()}>{api.title}</span>

      {api.showCloseIcon() && <KiCloseSolid {...api.getCloseIconProps()} />}
    </header>
  );
};

export default DialogHeader;

// packages/vue/src/dialog/DialogHeader.vue
<script setup lang="ts">
import useDialogHeader from "./useDialogHeader";
import { KiCloseSolid } from "@kedataindo/vue-icons";
import type { DialogHeaderProps } from "./index.types";

defineOptions({
  inheritAttrs: false,
});
const props = defineProps<DialogHeaderProps>();

const { showCloseIcon, title, ...api } = useDialogHeader(props);
</script>

<template>
  <header v-bind="api.getRootProps()">
    <span v-if="!!title" v-bind="api.getTitleProps()">
      {{ title }}
    </span>

    <KiCloseSolid v-if="showCloseIcon" v-bind="api.getCloseIconProps()" />
  </header>
</template>
