// packages/solid/src/swal-alert/swal-alert.tsx
import { Button } from '../button';
import { swalAlertSlots } from '@kedataindo/slots/swal-alert';
import tw from '@kedataindo/slots/tw';
import { dataAttrBoolean } from '@kedata-software/toolkit-js';
import clsx from 'clsx';
import { createMemo, createSignal } from 'solid-js';
import { render } from 'solid-js/web';
import Swal from 'sweetalert2';
import type { SwalAlertFireProps } from './index.types';
import useColorPalette from '../use-color-palette';

const SwalAlert = {
  fire<D = unknown>(props: SwalAlertFireProps<D>) {
    const { twMerge = tw.base } = props;

    Swal.fire({
      title: props.title,
      customClass: {
        container: twMerge(
          clsx(
            '[&>.swal2-popup]:pb-0',
            '[&_.swal2-html-container]:p-0 [&_.swal2-html-container]:text-base',
          ),
        ),
        title: twMerge(clsx('hidden')),
        htmlContainer: twMerge(clsx('p-0')),
      },
      didOpen(popup) {
        if (!popup.parentElement) return;

        popup.parentElement.querySelector('#swal2-title')?.remove();

        const actions = popup.querySelector('.swal2-actions');
        if (actions) {
          actions.remove();
        }

        const htmlContainer = popup.querySelector('.swal2-html-container');
        if (htmlContainer) {
          render(
            () => (
              <Alert
                twMerge={twMerge}
                {...props}
                showConfirmButton={props.showConfirmButton ?? true}
                showDenyButton={props.showDenyButton ?? true}
                onDeny={(result) => {
                  Swal.close();
                  props.onDeny?.(result);
                }}
                onConfirm={(result) => {
                  Swal.close();
                  props.onConfirm?.(result);
                }}
              />
            ),
            htmlContainer,
          );
        }
      },
    });
  },
};

export default SwalAlert;

function Alert<D>(inProps: SwalAlertFireProps<D>) {
  const props = inProps;
  const classNames = createMemo(() => inProps.classNames);
  const colorPaletteClass = useColorPalette(() => props.colorPalette);
  const { twMerge } = props;
  const [isConfirmLoading, setIsConfirmLoading] = createSignal(false);
  const [isDenyLoading, setIsDenyLoading] = createSignal(false);
  const isLoading = createMemo(() => isConfirmLoading() || isDenyLoading());

  const {
    root: getRootClassName,
    footer: getFooterClassName,
    title: getTitleClassName,
    content: getContentClassName,
    text: getTextClassName,
  } = swalAlertSlots(props);

  return (
    <div
      data-loading={dataAttrBoolean(isLoading)}
      class={twMerge?.(
        clsx(colorPaletteClass(), getRootClassName(), classNames()?.root),
      )}
    >
      <div
        class={twMerge?.(clsx(getContentClassName(), classNames()?.content))}
      >
        <div class={twMerge?.(clsx(getTitleClassName(), classNames()?.title))}>
          {props.title}
        </div>
        <p class={twMerge?.(clsx(getTextClassName(), classNames()?.text))}>
          {props.text}
        </p>
      </div>

      {(props.showConfirmButton || props.showDenyButton) && (
        <div
          class={twMerge?.(clsx(getFooterClassName(), classNames()?.footer))}
        >
          {props.showDenyButton && (
            <Button
              variant="outline"
              disabled={isConfirmLoading()}
              loading={isDenyLoading()}
              colorPalette={props.colorPalette}
              onClick={async () => {
                try {
                  let result: D | undefined = undefined;

                  if (props.preDeny) {
                    setIsDenyLoading(true);
                    result = await props.preDeny();
                    setIsDenyLoading(false);
                  }

                  props.onDeny?.({
                    isConfirmed: false,
                    isDenied: true,
                    isDismissed: false,
                    value: result,
                  });
                } catch (err) {
                  props.onDenyError?.(err);
                }
              }}
            >
              Batalkan
            </Button>
          )}

          {props.showConfirmButton && (
            <Button
              loading={isConfirmLoading()}
              disabled={isConfirmLoading()}
              colorPalette={props.colorPalette}
              onClick={async () => {
                try {
                  let result: D | undefined = undefined;

                  if (props.preConfirm) {
                    setIsConfirmLoading(true);
                    result = await props.preConfirm();
                    setIsConfirmLoading(false);
                  }

                  props.onConfirm?.({
                    isConfirmed: true,
                    isDenied: false,
                    isDismissed: false,
                    value: result,
                  });
                } catch (err) {
                  props.onConfirmError?.(err);
                }
              }}
            >
              Tutup
            </Button>
          )}
        </div>
      )}
    </div>
  );
}

// packages/vue/src/swal-alert/SwalAlert.vue
<script setup lang="ts" generic="D">
import { swalAlertSlots } from '@kedataindo/slots';
import { computed, ref } from 'vue';
import { Button } from '../button';
import type { SwalAlertProps } from './index.types';
import { useColorPalette } from '../use-color-palette';
import clsx from 'clsx';

defineOptions({
  inheritAttrs: false,
});

const props = defineProps<SwalAlertProps<D>>();
const emits = defineEmits(['confirm', 'deny']);
const slots = computed(() => {
  return swalAlertSlots({ withParts: true });
});

const colorPaletteClass = useColorPalette(() => props.colorPalette);

const isConfirmLoading = ref(false);
const isDenyLoading = ref(false);
</script>
<template>
  <div :class="clsx(slots.root(), colorPaletteClass)">
    <slot name="icon" v-bind="{ class: slots.icon() }" />

    <div :class="slots.content()">
      <div :class="slots.title()">
        <slot name="title" />
      </div>
      <div :class="slots.text()">
        <slot name="text" />
      </div>
    </div>

    <div
      v-if="props.showConfirmButton || props.showDenyButton"
      :class="slots.footer()"
    >
      <Button
        v-if="props.showDenyButton"
        variant="outline"
        :disabled="isConfirmLoading"
        :loading="isDenyLoading"
        :color-palette="props.colorPalette"
        @click="
          async () => {
            try {
              let result: D | undefined = undefined;

              if (props.preDeny) {
                isDenyLoading = true;
                result = await props.preDeny();
                isDenyLoading = false;
              }

              props.onDeny?.({
                isConfirmed: false,
                isDenied: true,
                isDismissed: false,
                value: result,
              });
            } catch (err) {
              props.onDenyError?.(err);
            }
          }
        "
      >
        <slot name="deny-button-text" />
      </Button>

      <Button
        v-if="props.showConfirmButton"
        :disabled="isDenyLoading"
        :loading="isConfirmLoading"
        variant="solid"
        :color-palette="props.colorPalette"
        @click="
          async () => {
            try {
              let result: D | undefined = undefined;

              if (props.preConfirm) {
                isConfirmLoading = true;
                result = await props.preConfirm();
                isConfirmLoading = false;
              }

              props.onConfirm?.({
                isConfirmed: true,
                isDenied: false,
                isDismissed: false,
                value: result,
              });
            } catch (err) {
              props.onConfirmError?.(err);
            }
          }
        "
      >
        <slot name="confirm-button-text" />
      </Button>
    </div>
  </div>
</template>
